---
title: "Análise Areia Muito Fina"
author: "Leonardo P. Migliorini"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width = 6, fig.height = 4.5)
```

```{r, include = FALSE}
# Loading packages -------------------------------------------------------------
library(geoR)
library(knitr)

# Loading data -----------------------------------------------------------------

(geodados <- read.geodata("AMF.txt", h = T))
```

Abaixo, temos os gráficos da malha de pontos amostrados, os valores da variável AMF versus as coordenadas do sistema de referência (X e Y), e o histograma mostrando a dispersão da variável AMF. 

```{r}
plot(geodados, lowes = TRUE)
```

```{r}
plot(geodados, trend = "1st", lowes = TRUE)
```



```{r}
# Estimando o semivariograma (Semivariograma amostral)
hmax1 <- summary(geodados)[[3]][[2]] * 0.9

hmax2 <- summary(geodados)[[3]][[2]] * 0.8

vario1 <- variog(geodados, trend = "1st", estimator = "classical", max.dist = hmax1)
vario2 <- variog(geodados, trend = "1st", estimator = "classical", max.dist = hmax2)

vario3 <- variog(geodados, trend = "1st", estimator = "modulus", max.dist = hmax1)
vario4 <- variog(geodados, trend = "1st", estimator = "modulus", max.dist = hmax2)

par(mfrow = c(2, 2))
plot(vario1, xlab = "Distância (h)", ylab = "Semivariância", sub = "hmax 90% - clássico")
plot(vario2, xlab = "Distância (h)", ylab = "Semivariância", sub = "hmax 80% - clássico")
plot(vario3, xlab = "Distância (h)", ylab = "Semivariância", sub = "hmax 90% - robusto")
plot(vario4, xlab = "Distância (h)", ylab = "Semivariância", sub = "hmax 80% - robusto")
```

```{r}
par(mfrow = c(1, 1))
vario.env <- variog.mc.env(geodados, obj.var = vario2)
plot(vario2, envelope = vario.env)
```

```{r}
# Avaliação da anisotropia:
var4 <- variog4(geodados, trend = "1st", max.dist = hmax2) # Gera semivariogramas em 4 direções principais
plot(var4)
```

```{r, include = FALSE}
# Ajuste de modelo esférico em cada direção:

vario <- variog(geodados, trend = "1st", estimator = "classical", max.dist = hmax2, direction = "omnidirectional") # geral
sph <- variofit(vario, cov.model = "sph", weights = "npairs")

vario1 <- variog(geodados, trend = "1st", estimator = "classical", max.dist = hmax2, direction = 0) # direção 0º
sph1 <- variofit(vario1, cov.model = "sph", weights = "npairs")

vario2 <- variog(geodados, trend = "1st", estimator = "classical", max.dist = hmax2, direction = pi / 4) # direção 45º
sph2 <- variofit(vario2, cov.model = "sph", weights = "npairs")

vario3 <- variog(geodados, trend = "1st", estimator = "classical", max.dist = hmax2, direction = pi / 2) # direção 90º
sph3 <- variofit(vario3, cov.model = "sph", weights = "npairs")

vario4 <- variog(geodados, trend = "1st", estimator = "classical", max.dist = hmax2, direction = 3 * pi / 4) # direção 135º
sph4 <- variofit(vario4, cov.model = "sph", weights = "npairs")
```


```{r}
par(mfrow = c(1, 1))
plot(vario, xlab = "Distância (h)", ylab = "Semivariância")
lines(sph, lwd = 1, lty = 1, col = "gray")   # omnidirecional
lines(sph1, lwd = 1, lty = 1, col = "black") # 0°
lines(sph2, lwd = 1, lty = 1, col = "red")   # 45°
lines(sph3, lwd = 1, lty = 1, col = "green") # 90°
lines(sph4, lwd = 1, lty = 1, col = "blue")  # 135°

legend("bottomright", 
       legend = c("Omnidirecional", "0º", "45º", "90º", "135º"),
       col = c("gray", "black", "red", "green", "blue"),
       lwd = 1, lty = 1, cex = 0.8, bty = "n")

```

```{r, include = FALSE}
# Avaliação dos parâmetros estimados (Alcance prático - Anisotropia geométrica):
# 0º
sph1[[8]]
# 45º
sph2[[8]]
# 90º
sph3[[8]]
# 135º
sph4[[8]]
# omnidirecional
sph[[8]]

# Identificação do maior alcance (a_max) e do menor alcance (a_min):
(a_max <- max(sph1[[8]], sph2[[8]], sph3[[8]], sph4[[8]]))
(a_min <- min(sph1[[8]], sph2[[8]], sph3[[8]], sph4[[8]]))

# Razão de anisotropia geometrica:

Fa <- a_max / a_min

# Avaliação dos parâmetros estimados (Patamar - Anisotropia zonal):
# 0º
sph1[[1]] + sph1[[2]][[1]]
# 45º
sph2[[1]] + sph2[[2]][[1]]
# 90º
sph3[[1]] + sph3[[2]][[1]]
# 135º
sph4[[1]] + sph4[[2]][[1]]
# omnidirecional
sph[[1]] + sph[[2]][[1]]

# Identificação do maior patamar (C_max) e do menor patamar (C_min):
(C_max <- max(
  sph1[[1]] + sph1[[2]][[1]], sph2[[1]] + sph2[[2]][[1]],
  sph3[[1]] + sph3[[2]][[1]], sph4[[1]] + sph4[[2]][[1]]
))
(C_min <- min(
  sph1[[1]] + sph1[[2]][[1]], sph2[[1]] + sph2[[2]][[1]],
  sph3[[1]] + sph3[[2]][[1]], sph4[[1]] + sph4[[2]][[1]]
))

# Razão de anisotropia zonal:
FC <- C_max / C_min

```

Dizer qual o ângulo de anisotropia 


```{r}
# Correção da anisotropia geométrica:
# Transformação das coordenadas de acrodo com os parâmetros de anisotropia:

coordsA <- coords.aniso(geodados$coords, aniso.pars = c(pi / 2, Fa))
# plot com as coordenadas originais (anisotropia) e o plot das
# 	coordenadas corrigidas (isotropia):
par(mfrow = c(1, 2))
plot(geodados$coords)
plot(coordsA)

```

```{r, include = FALSE}
# Novo geodados:
dados <- cbind(coordsA, geodados$data)
geodadosc <- as.geodata(dados)
```

```{r}
# Semivariogramas nas 4 direções principais após correção da anisotropia:
hmaxc <- summary(geodadosc)[[3]][[2]] * 0.8
var4c <- variog4(geodadosc, trend = "1st", estimator = "classical", max.dist = hmaxc)

# 4 direções com coordenadas originais e 4 direções com coordenadas corrigidas:
par(mfrow = c(1, 2))
plot(var4)
plot(var4c)
```

```{r, include = FALSE}
# Ajuste final (após correção da anisotropia - Semivariograma omnidirecional):

varioc <- variog(geodadosc, trend = "1st", estimator = "classical", max.dist = hmaxc, direction = "omnidirectional")
sphc <- variofit(varioc, cov.model = "sph", weights = "npairs")

```

```{r}
par(mfrow = c(1, 1))
plot(varioc, xlab = "Distancia (h)", ylab = "Semivariancia", sub = "final")
lines(sphc, lwd = 1, lty = 1, col = "red")
```

Comentar valores dos parâmetros do modelo final c0 c1 c a

Inserir tabela depois

```{r}
dados_esferico <- data.frame(
  Estimativas = c("EP", "CT", "AL", "MinimaSQ", "", "", "EM", "ER", "Dpem", "Ser", "EA", "B0", "B1"),
  OLS   = c(0, 2.3, 114.06, 1.4345, "", "", 0.00996, 0.00543, 0.79186, 0.82375, 76.3996, 0.25416, 0.95428),
  MLS   = c(0, 2.3, 114.06, 613.7262, "", "", 0.11681, 0.0076, 0.79805, 0.90343, 77.70022, 0.59124, 0.89145),
  Cre   = c(0.77, 1.53, 171.09, 137.8317, "", "", 0.00923, 0.00484, 0.7927, 0.81352, 76.65897, 0.15567, 0.97258),
  MV    = c(0.1586, 1.9635, 124.071, "AIC/BIC", 363.8898, 380.7139, 0.01176, 0.00668, 0.78143, 0.83575, 74.49706, 0.27335, 0.951),
  REML  = c(0.1333, 2.1361, 125.3123, "AIC/BIC", 350.9683, 367.7924, 0.01166, 0.00662, 0.78396, 0.83667, 74.98033, 0.33515, 0.93941)
)

kable(dados_esferico, caption = "Estimativas para o modelo esférico")
```

```{r}
exponencial <- data.frame(
  Estatistica = c("EP", "CT", "AL", "MinimaSQ", "", "", 
                  "EM", "ER", "Dpem", "Ser", "EA", "B0", "B1"),
  OLS   = c(0, 2.3, 57.03, 1.6933, "", "", 0.01105, 0.00555, 0.79975, 0.80121, 78.031, 0.23329, 0.95584),
  MLS   = c(0, 2.3, 57.03, 770.9322, "", "", 0.11879, 0.00571, 0.80037, 0.7878, 78.15279, 0.15723, 0.97278),
  Cre   = c(0, 2.3, 57.03, 177.8137, "", "", 0.01098, 0.00539, 0.79873, 0.79165, 77.83325, 0.18325, 0.96774),
  MV    = c(0.1233, 3.4929, 129.999, "AIC/BIC", 367.7111, 384.5352, 0.00531, 0.00326, 0.79129, 0.84323, 76.38815, 0.28946, 0.94684),
  REML  = c(0.897, 3.7937, 130.000, "AIC/BIC", 350.4786, 367.3027, 0.00525, 0.00327, 0.79269, 0.84325, 76.66044, 0.35993, 0.93337)
)

kable(exponencial, caption = "Estatísticas para o modelo exponencial")

```

```{r}
gaussiano <- data.frame(
  Estatistica = c("EP", "CT", "AL", "MinimaSQ", "", "", 
                  "EM", "ER", "Dpem", "Ser", "EA", "B0", "B1"),
  OLS   = c(0, 2.3, 57.03, 1.4134, "", "", 0.01022, 0.00575, 0.76753, 0.8176, 71.8698, 0.25416, 0.95428),
  MLS   = c(0, 2.3, 57.03, 612.485, "", "", 0.11725, 0.00832, 0.77939, 0.91177, 74.10791, 0.59124, 0.89145),
  Cre   = c(0.77, 1.53, 57.03, 130.143, "", "", 0.00952, 0.00522, 0.76834, 0.81071, 72.0221, 0.15567, 0.97248),
  MV    = c(0.5833, 2.2347, 75.9108, "AIC/BIC", 359.3342, 376.1583, 0.00827, 0.00482, 0.76933, 0.83592, 72.2076, 0.27335, 0.951),
REML  = c(0.4864, 2.7574, 80.0117, "AIC/BIC", 344.5574, 361.3815, 0.00757, 0.00442, 0.77153, 0.83832, 72.62136, 0.33515, 0.93941)
)

kable(gaussiano, caption = "Estatísticas para o modelo gaussiano")

```

```{r, include = FALSE}

gaus.wls2 <- variofit(varioc, cov.model = "gaus", weights = "cressie")
```



```{r, include = FALSE}
# Índice DE proposto por Biondi et al. (1994):
# Estimativas dos parâmetros do semivariograma:
C0 <- 0.5374 # efeito pepita
  C1 <- 1.8074 # contribuição
  #
  I <- if (C1 == 0) {
    I <- 0
  } else {
    I <- C1 / (C0 + C1)
  }

# DE
DE <- I * 100

# Classificação do DE (adaptada de Cambardella et al. (1994))
if (DE < 25) {
  cat("Fraca dependência espacial")
} else if (DE >= 25 && DE < 75) {
  cat("Moderada dependência espacial")
} else {
  cat("Forte dependência espacial")
}
# Índice IDE proposto por Seidel e Oliveira (2014, 2016):
# Estimativas dos parâmetros do semivariograma:
C0 <- 0.5374 # efeito pepita
  C1 <- 1.8074 # contribuição
  a <- 69.1901# alcance prático
  MD <- 901.3878# máxima distância
  I <- if (C1 == 0) {
    I <- 0
  } else {
    I <- C1 / (C0 + C1)
  }
II <- if (a >= (0.5 * MD)) {
  II <- 1
} else {
  II <- a / (0.5 * MD)
}
# IDE no modelo Gaussiano
IDE_gaus <- 0.504 * I * II * 100
# Classificação do IDE_gaus
if (IDE_gaus < 9) {
  cat("Fraca dependência espacial")
} else if (IDE_gaus >= 9 && IDE_gaus < 20) {
  cat("Moderada dependência espacial")
} else {
  cat("Forte dependência espacial")
}
```
